name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - michabirklbauer
  - louisebuur
  - MarinaStrobl
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: version-ms-amanda
    attributes:
      label: MS Amanda Version
      description: What version of MS Amanda are you running?
      placeholder: MS Amanda Standalone v3.0.22.071
    validations:
      required: true
  - type: textarea
    id: version-proteome-discoverer
    attributes:
      label: Proteome Discoverer Version
      description: What version of Proteome Discoverer are you running (if you are not using the standalone)?
      placeholder: Proteome Discoverer 3.1
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Thanks for getting in touch with us - in case you want us to reply via email please leave your contact info.
      placeholder: ex. email@example.com
    validations:
      required: false
