name: Feature Request
description: Request a new feature for MS Amanda.
title: "[Feature Request]: "
labels: ["enhancement"]
assignees:
  - michabirklbauer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for MS Amanda!
  - type: textarea
    id: feature-request
    attributes:
      label: What feature would you like to see in MS Amanda?
      description: Please give us as many details as possible for what you would like to do.
      placeholder: I want...!
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Thanks for getting in touch with us - in case you want us to reply via email please leave your contact info.
      placeholder: ex. email@example.com
    validations:
      required: false
